### ISSUE TITLE
UWP版呢？

### ISSUE THREAD

**Issue by h82258652** [EdiWang/QRCodeCreator#1]
RT。
PS：我是来捣乱的![moren_hashiqi_thumb](https://cloud.githubusercontent.com/assets/5144550/23403351/b857c25c-fdea-11e6-9824-8e4d6a17b38d.png)

**Comment by EdiWang** [comment]
早就有了……
https://www.microsoft.com/en-us/store/p/simple-qrcode-creator/9nblggh67tv2

________________________________

**Comment by h82258652** [comment]
那把核心部分代码合并下吧![qq 20170228214820](https://cloud.githubusercontent.com/assets/5144550/23407588/a5eb2c70-fdff-11e6-83a5-62eab923551b.png)

**Comment by EdiWang** [comment]
Close as already implemented
